### ISSUE TITLE
Export results in traceback/error (revision 4493206b987e3813862c924aab339e4a67e232d7)

### ISSUE THREAD

**Issue by JonasT** [09th/YABEE#17]
I just tried to export a model (link below), and this is the error I get on the console:

```
jonas@cyberman:~$ blender
connect failed: No such file or directory
read blend: /home/jonas/Develop/3dhorror/gfx/part1.blend
reloading addon: YABEE-master 1435426492.985045 1435426639.1908436 /home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/__init__.py
Modules Installed from '/home/jonas/Downloads/YABEE-master.zip' into '/home/jonas/.config/blender/2.72/scripts/addons' ()
reloading addon: YABEE-master 1435426639.1908436 1435426659.6310947 /home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/__init__.py
Modules Installed from '/home/jonas/Downloads/YABEE-master.zip' into '/home/jonas/.config/blender/2.72/scripts/addons' ()
trying to save userpref at /home/jonas/.config/blender/2.72/config/userpref.blend ok
Objects for export: ['Cylinder']
WRITE main EGG to /home/jonas/Develop/3dhorror/gfx/part1.egg
COPY IMAGE /home/jonas/Develop/3dhorror/gfx/level/objects/pipemetal.png to /home/jonas/Develop/3dhorror/gfx/tex/pipemetal.png; rel path ./tex/pipemetal.png
COPY IMAGE /home/jonas/Develop/3dhorror/gfx/level/floor/tiled01.png to /home/jonas/Develop/3dhorror/gfx/tex/tiled01.png; rel path ./tex/tiled01.png
COPY IMAGE /home/jonas/Develop/3dhorror/gfx/level/wall/concrete01.png to /home/jonas/Develop/3dhorror/gfx/tex/concrete01.png; rel path ./tex/concrete01.png
COPY IMAGE /home/jonas/Develop/3dhorror/gfx/level/wall/concrete02.png to /home/jonas/Develop/3dhorror/gfx/tex/concrete02.png; rel path ./tex/concrete02.png
COPY IMAGE /home/jonas/Develop/3dhorror/gfx/level/ceiling/concrete1.png to /home/jonas/Develop/3dhorror/gfx/tex/concrete1.png; rel path ./tex/concrete1.png
Traceback (most recent call last):
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 1532, in write_out
    file.write(gr.get_full_egg_str())
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 181, in get_full_egg_str
    return ''.join(self.get_full_egg_str_arr(level))
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 214, in get_full_egg_str_arr
    egg_str.append( ch.get_full_egg_str(level + 1) )
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 181, in get_full_egg_str
    return ''.join(self.get_full_egg_str_arr(level))
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 207, in get_full_egg_str_arr
    for line in self._yabee_object.get_full_egg_str().splitlines():
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 875, in get_full_egg_str
    self.get_polygons_str()))
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 867, in get_polygons_str
    polygons = '\n' + ''.join(self.collect_polygons())
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 840, in collect_polygons
    tref(f, attributes)
  File "/home/jonas/.config/blender/2.72/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 715, in collect_poly_tref
    tex_name = used_textures.get(facedata.image.yabee_name, None)
NameError: name 'used_textures' is not defined
```
This is the model causing the error for me: http://www.homeofjones.de/temp/part1packed.blend
blender 2.72 on Ubuntu 15.04 x86_64 with the egg tools from recent panda3d master revision

**Comment by JonasT** [comment]
Replacing all occurances of USED_TEXTURES in yabee_libs/egg_writer.py with used_textures seems to fix it. (I guess the other way round would also work)

**Comment by JonasT** [comment]
Sorry the replacing above makes it not error but doesn't actually work: I get all white textures.

I went back to 2343369ccb84d52590fc03be714c0e812a653772 now since that one still works.

**Comment by 09th** [comment]
Ok, fix pushed, try it plz.
